CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('Admin', 'DPO', 'User'))
);

CREATE TABLE IF NOT EXISTS consents (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    touchpoint_name TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('Active', 'Pending', 'Revoked')),
    timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dsr_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    request_type TEXT NOT NULL CHECK (request_type IN ('Access', 'Rectification', 'Erasure', 'Restriction', 'Portability', 'Objection')),
    description TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Under Review', 'Approved', 'Denied', 'Completed')),
    submitted_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMPTZ,
    resolution_notes TEXT
);

CREATE TABLE IF NOT EXISTS incidents (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reported_by_id INTEGER NOT NULL REFERENCES users(id),
    timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    status TEXT NOT NULL DEFAULT 'New' CHECK (status IN ('New', 'Under Investigation', 'Resolved', 'Closed')),
    severity TEXT NOT NULL DEFAULT 'Low' CHECK (severity IN ('Low', 'Medium', 'High', 'Critical')),
    breach_category TEXT CHECK (breach_category IN ('Confidentiality', 'Integrity', 'Availability')),
    discovery_timestamp TIMESTAMPTZ,
    npc_notified BOOLEAN NOT NULL DEFAULT FALSE,
    description TEXT NOT NULL,
    assigned_to_id INTEGER REFERENCES users(id),
    resolution_details TEXT
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    user_identity TEXT NOT NULL,
    action_type TEXT NOT NULL CHECK (action_type IN ('CREATE', 'READ', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'EXPORT')),
    source_ip TEXT,
    description TEXT,
    json_payload TEXT
);

CREATE TABLE IF NOT EXISTS processing_registry (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_name TEXT NOT NULL,
    purpose TEXT NOT NULL,
    data_categories TEXT NOT NULL,
    legal_basis TEXT NOT NULL,
    retention_period TEXT NOT NULL,
    owner TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS privacy_notices (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    version TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ,
    is_published BOOLEAN NOT NULL DEFAULT FALSE,
    published_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS personal_data_inventory (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_item TEXT NOT NULL,
    category TEXT NOT NULL,
    purpose TEXT NOT NULL,
    storage_location TEXT NOT NULL,
    data_type TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS compliance_checklist (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('Compliant', 'Non-Compliant', 'In-Progress')),
    notes TEXT,
    last_reviewed TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
